name: Build

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 📦 Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js lts/*
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: 📦 Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: 🌌 Build Valaxy Blog
        run: pnpm run build
